- name: "Configure a basic NetBox with a Cisco device"
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
  tasks:
    - name: Create site with all parameters
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: cisco-live-emea
          slug: cisco-live-emea
        state: present

    - name: Create manufacturer within NetBox with only required information
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: cisco
        state: present

    - name: Create device type within NetBox with only required information
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          slug: cisco-c8000v
          model: C8000V
          manufacturer: cisco
        state: present

    - name: Create device role within NetBox with only required information
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: Edge Router
          color: FFFFFF
        state: present
    
    - name: Create a custom field on device and virtual machine
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          content_types:
            - dcim.device
          name: host
          type: text
    
    - name: Create a custom field on device and virtual machine
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          content_types:
            - dcim.device
          name: port
          type: text

    - name: Create platform within NetBox with only required information
      netbox.netbox.netbox_platform:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: cisco.ios.ios
          slug: cisco-ios-ios
          manufacturer: cisco
        state: present

    - name: Create device within NetBox with only required information
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: cat1
          device_type: cisco-c8000v
          device_role: Edge Router
          site: cisco-live-emea
        state: present